export const servicesData = {
  "tax-compliance": {
    slug: "tax-compliance",
    title: "Tax Compliance",
    primaryKeyword: "tax compliance tax return filing CPA Irving TX",
    overviewTitle: "Accurate & Timely Tax Return Filing for Individuals and Businesses",
    overview: "At VS Tax CPA LLC, we handle all aspects of tax compliance — preparing and filing accurate federal and state tax returns for individuals, businesses, trusts, estates, and exempt organizations. Our licensed CPA ensures every return is filed on time, every deduction is captured, and your exposure to penalties or audits is minimized.",
    whatWeOffer: [
      { title: "Individual Tax Returns (1040)", desc: "Accurate preparation and e-filing of federal and Texas state individual income tax returns, including complex situations like rental income, self-employment, stock options, and multi-state filings." },
      { title: "Business Tax Returns", desc: "Complete preparation of S-Corp (1120-S), C-Corp (1120), Partnership (1065), and LLC returns with a strategic eye on minimizing tax liability." },
      { title: "Trust & Estate Returns (1041)", desc: "Expert filings for trusts, estates, and fiduciaries ensuring compliance with all income distribution and beneficiary reporting requirements." },
      { title: "Non-Profit & Exempt Organizations (990)", desc: "Timely 990/990-EZ/990-N preparation for non-profit and exempt organizations, maintaining your tax-exempt status." },
    ],
    benefits: [
      { title: "Zero Penalty Compliance", desc: "We track all filing deadlines — federal, state, and local — to keep you fully compliant and penalty-free." },
      { title: "Maximum Deductions Captured", desc: "Our thorough review ensures no legal deduction is missed, putting more money back in your pocket." },
      { title: "Licensed Texas CPA Review", desc: "Every return is personally reviewed by Vethavalli Ramakrishnan, CPA — licensed by the Texas State Board of Public Accountancy." },
      { title: "Audit-Ready Documentation", desc: "We prepare and organize supporting documentation so you're always prepared if the IRS or state comes knocking." },
    ],
    process: [
      { num: "01", title: "Document Collection", desc: "We provide a clear checklist and securely collect all required financial documents, W-2s, 1099s, and business records." },
      { num: "02", title: "Review & Analysis", desc: "Our CPA reviews your complete financial picture, identifying all allowable deductions, credits, and strategic opportunities." },
      { num: "03", title: "Preparation & Verification", desc: "We prepare your return using professional tax software, cross-checking for accuracy and compliance." },
      { num: "04", title: "Filing & Delivery", desc: "Returns are e-filed and you receive a complete copy along with a summary of your tax position and any recommended next steps." },
    ],
    industries: ["Real Estate & Rental Properties", "Restaurants & Hospitality", "Dental Practices", "IT Services & Tech Startups", "Staffing Companies", "Manufacturing", "Contractors & Construction", "Artists & Creators"],
    documents: [
      "W-2s, 1099s, and K-1 forms",
      "Prior year tax returns",
      "Business income and expense records",
      "Mortgage interest and property tax statements",
      "Retirement account contribution records",
      "Charitable donation receipts",
    ],
    faqs: [
      { q: "What types of returns does VS Tax CPA LLC file?", a: "We file individual (1040), S-Corp (1120-S), C-Corp (1120), Partnership (1065), LLC, Trust/Estate (1041), Non-Profit (990), and state income tax returns." },
      { q: "What is the filing deadline for individual taxes?", a: "The standard federal deadline is April 15. We can file extensions to October 15 when needed, but payments are still due April 15." },
      { q: "Do you handle multi-state tax returns?", a: "Yes. We handle multi-state filings for clients who live or work in multiple states — common for remote workers, real estate investors, and traveling professionals." },
      { q: "How do I send my documents securely?", a: "We use a secure client portal for all document uploads and communication to protect your sensitive financial information." },
      { q: "What if I haven't filed taxes in several years?", a: "We specialize in back-tax filing and can help you get compliant with the IRS and minimize any resulting penalties." },
      { q: "Do I owe state income tax in Texas?", a: "Texas has no state individual income tax, but businesses may owe Texas Franchise Tax. We handle both." },
    ],
    related: ["tax-planning", "irs-representation", "bookkeeping"],
    uniqueData: {
      checklist: [
        "All income statements (W-2, 1099-NEC, 1099-B, K-1) gathered",
        "Prior year return reviewed for carryovers",
        "Business expense categories organized",
        "Rental income/expenses documented",
        "Retirement contributions verified",
      ],
      calendar: [
        { date: "Jan 31", task: "W-2 & 1099 Issuance Deadline" },
        { date: "Mar 15", task: "S-Corp & Partnership Return Deadline (or Extension)" },
        { date: "Apr 15", task: "Individual & C-Corp Return Deadline + Q1 Estimated Tax Due" },
        { date: "Oct 15", task: "Extended Individual Return Deadline" },
      ],
    },
  },

  "tax-planning": {
    slug: "tax-planning",
    title: "Tax Planning & Advisory",
    primaryKeyword: "tax planning advisory CPA Irving TX minimize taxes",
    overviewTitle: "Proactive Year-Round Tax Planning to Maximize Savings",
    overview: "Tax planning at VS Tax CPA LLC is not a once-a-year event — it's a strategic, year-round process. We analyze your current and projected income, business structure, investments, and personal situation to craft a customized plan that legally minimizes your tax liability and maximizes your after-tax wealth.",
    whatWeOffer: [
      { title: "Year-Round Tax Strategy", desc: "Ongoing advisory throughout the year — not just at tax season — to proactively identify opportunities and avoid costly surprises." },
      { title: "Entity Structure Optimization", desc: "Determine the ideal business structure (LLC, S-Corp, C-Corp) to minimize self-employment taxes and maximize deductions." },
      { title: "Estimated Tax Planning", desc: "Calculate accurate quarterly estimated tax payments so you avoid underpayment penalties and never face a massive April bill." },
      { title: "Retirement & Investment Tax Strategy", desc: "Strategic use of retirement accounts (SEP-IRA, Solo 401k, SIMPLE IRA) and tax-loss harvesting to reduce taxable income." },
    ],
    benefits: [
      { title: "Significant Tax Savings", desc: "Clients typically save thousands to tens of thousands in taxes annually through proactive restructuring and deduction maximization." },
      { title: "No Surprises at Tax Time", desc: "Stay fully informed throughout the year with scheduled reviews, estimated payment reminders, and proactive alerts on law changes." },
      { title: "Personalized Strategy", desc: "Every plan is tailored to your specific industry, business stage, family situation, and financial goals — not a one-size-fits-all approach." },
      { title: "Long-Term Wealth Building", desc: "Strategic planning around retirement accounts, capital gains timing, and business exits to build lasting financial security." },
    ],
    process: [
      { num: "01", title: "Financial Deep Dive", desc: "Comprehensive review of your last 2-3 years of tax returns, income sources, investments, and business structure." },
      { num: "02", title: "Strategy Development", desc: "Identify opportunities across entity structure, retirement contributions, deductions, credits, and income timing strategies." },
      { num: "03", title: "Implementation", desc: "Guide you through specific action steps — from payroll adjustments to retirement account setup to entity restructuring." },
      { num: "04", title: "Ongoing Review & Monitoring", desc: "Quarterly check-ins, mid-year reviews, and proactive communication on tax law changes affecting your strategy." },
    ],
    industries: ["Real Estate Investors", "Dental Practices", "IT Services & Consultants", "Restaurants & Hospitality", "Contractors", "Staffing Companies", "Manufacturing"],
    documents: [
      "Last 2-3 years of tax returns",
      "Current year income projections",
      "Business profit & loss statements",
      "Investment and brokerage account statements",
      "Retirement account balances and contribution history",
    ],
    faqs: [
      { q: "When should I start tax planning?", a: "Ideally, tax planning is a year-round process. The best time to start is now — mid-year strategies have just as much impact as end-of-year moves." },
      { q: "How much can I realistically save through tax planning?", a: "Savings vary widely based on income, structure, and opportunities identified. Many clients save $5,000–$50,000+ annually with proactive planning." },
      { q: "Should I form an S-Corp to save on self-employment taxes?", a: "Potentially yes. S-Corps can save self-employed individuals significant FICA taxes when income exceeds certain thresholds. We analyze your specific situation to determine if this makes sense." },
      { q: "What retirement accounts can a self-employed person use?", a: "Self-employed individuals can use SEP-IRA (up to 25% of net earnings), Solo 401(k) (up to $69,000 in 2024), and SIMPLE IRA. We help you choose and set up the right account." },
      { q: "How do estimated tax payments work?", a: "Self-employed individuals and business owners typically pay taxes quarterly (April 15, June 15, September 15, January 15). We calculate and remind you of the exact amounts." },
    ],
    related: ["tax-compliance", "business-formation", "fractional-cfo"],
    uniqueData: {
      tips: [
        { category: "Entity Structure", tip: "Elect S-Corp status at the right income threshold to eliminate self-employment tax on a portion of your earnings." },
        { category: "Retirement", tip: "Max out a Solo 401(k) to shelter up to $69,000 per year from taxes while building long-term wealth." },
        { category: "Real Estate", tip: "Use cost segregation and bonus depreciation to dramatically accelerate deductions on investment properties." },
        { category: "Home Office", tip: "Properly document and claim the home office deduction if you operate your business from home — often $3,000–$8,000 annually." },
        { category: "Vehicles", tip: "Track business mileage or elect bonus depreciation on a heavy SUV or vehicle used for business." },
      ],
      deadlines: [
        { date: "April 15", event: "Q1 Estimated Tax Payment Due" },
        { date: "June 15", event: "Q2 Estimated Tax Payment Due" },
        { date: "September 15", event: "Q3 Estimated Tax Payment Due" },
        { date: "January 15", event: "Q4 Estimated Tax Payment Due" },
      ],
    },
  },

  "business-formation": {
    slug: "business-formation",
    title: "Business Entity Formation",
    primaryKeyword: "business entity formation LLC S-Corp CPA Irving TX",
    overviewTitle: "Launch Your Business with the Right Legal & Tax Structure",
    overview: "Starting a business involves critical structural decisions that have lasting tax and liability implications. VS Tax CPA LLC guides entrepreneurs and established business owners through choosing the right entity type, completing all state and federal registrations, and setting up your financial foundation for long-term success.",
    whatWeOffer: [
      { title: "Entity Selection & Advisory", desc: "Guidance on choosing between Sole Proprietor, LLC, S-Corp, C-Corp, or Partnership based on your tax goals, liability needs, and business plan." },
      { title: "Texas State Filings", desc: "Complete Texas Secretary of State formation filings, Registered Agent setup, and operating agreement or bylaws preparation." },
      { title: "Federal EIN Registration", desc: "Apply for your Federal Employer Identification Number (EIN) required for banking, payroll, and tax filings." },
      { title: "S-Corp Election (Form 2553)", desc: "Timely filing of IRS Form 2553 to elect S-Corporation status and immediately begin capturing self-employment tax savings." },
    ],
    benefits: [
      { title: "Liability Protection", desc: "Proper entity formation separates your personal assets from business liabilities, protecting your home, savings, and personal property." },
      { title: "Immediate Tax Savings", desc: "Choosing the right entity from day one — especially S-Corp election — can save thousands in self-employment taxes annually." },
      { title: "Credibility & Professionalism", desc: "Operating as a registered LLC or Corp builds trust with clients, vendors, and lenders who prefer to work with formal legal entities." },
      { title: "Foundation for Growth", desc: "A correctly structured entity from the start makes it easier to add partners, secure funding, and eventually sell the business." },
    ],
    process: [
      { num: "01", title: "Discovery & Goals", desc: "Understand your business model, ownership structure, projected income, liability concerns, and growth plans." },
      { num: "02", title: "Entity Recommendation", desc: "Present a clear recommendation for the optimal entity type with a tax projection showing the annual savings impact." },
      { num: "03", title: "Formation Filing", desc: "Prepare and file all required state and federal documents — Texas SOS, EIN application, S-Corp election (if applicable)." },
      { num: "04", title: "Financial Setup Guidance", desc: "Advise on business bank account setup, accounting software, initial recordkeeping, and payroll requirements." },
    ],
    industries: ["IT Services & Freelancers", "Dental Practices", "Contractors & Trades", "Real Estate Investors", "Restaurants", "Staffing Companies", "Manufacturing"],
    documents: [
      "Owner identification (SSN or ITIN)",
      "Proposed business name and address",
      "Ownership structure and percentage breakdown",
      "Business description and industry",
      "Projected annual revenue (for entity optimization)",
    ],
    faqs: [
      { q: "Should I form an LLC or S-Corp?", a: "An LLC provides flexibility and liability protection. An S-Corp election on top of an LLC adds self-employment tax savings once net income exceeds roughly $40,000-$50,000. We run the numbers for your situation." },
      { q: "How long does it take to form a Texas LLC?", a: "Texas Secretary of State typically processes formations within 2-3 business days for standard filings, or same day with expedited processing." },
      { q: "Do I need an operating agreement?", a: "Yes. Even single-member LLCs benefit from an operating agreement to solidify the separation between personal and business, which is important for legal protection." },
      { q: "What is an EIN and do I need one?", a: "An Employer Identification Number (EIN) is your business's federal tax ID. You need it to open a business bank account, hire employees, and file business tax returns." },
      { q: "Can I change my entity type later?", a: "Yes, but changes later can have tax consequences. Getting it right from the start avoids complexity and saves money over the long term." },
    ],
    related: ["tax-planning", "payroll-services", "bookkeeping"],
    uniqueData: {
      checklist: [
        "Business name availability checked with Texas SOS",
        "Entity type selected based on tax projection",
        "Registered agent identified (can be Vethavalli/VS Tax CPA LLC)",
        "Operating agreement or bylaws drafted",
        "EIN obtained from IRS",
        "Business bank account opened",
      ],
      calendar: [
        { date: "Day 1", task: "Texas SOS Entity Formation Filing" },
        { date: "Day 3-5", task: "EIN Obtainment & Business Bank Account Setup" },
        { date: "Day 7", task: "S-Corp Election Filing (Form 2553) if applicable" },
        { date: "Month 1", task: "Accounting System & Payroll Setup" },
      ],
    },
  },

  "payroll-services": {
    slug: "payroll-services",
    title: "Payroll Set Up & Management",
    primaryKeyword: "payroll setup Gusto CPA Irving TX small business payroll",
    overviewTitle: "Seamless Payroll Setup & Management Powered by Gusto",
    overview: "Payroll compliance is one of the most complex and risk-laden areas for small business owners. VS Tax CPA LLC sets up and manages your payroll through Gusto — one of the most intuitive and robust payroll platforms available — ensuring accurate pay runs, correct tax withholdings, on-time deposits, and full payroll tax compliance.",
    whatWeOffer: [
      { title: "Gusto Payroll Setup & Onboarding", desc: "Full setup of your Gusto payroll account including employee onboarding, direct deposit, benefits integration, and tax configuration." },
      { title: "Payroll Processing & Pay Runs", desc: "Accurate, timely payroll processing for W-2 employees and 1099 contractors, including automated direct deposits." },
      { title: "Payroll Tax Deposits & Filings", desc: "Timely federal (941/944) and Texas state payroll tax deposits, and accurate quarterly and annual payroll tax filings (940, W-2, W-3)." },
      { title: "S-Corp Reasonable Compensation", desc: "Establish and maintain IRS-compliant reasonable salary for S-Corp owner-operators to maximize self-employment tax savings." },
    ],
    benefits: [
      { title: "Zero Payroll Penalties", desc: "Late payroll tax deposits attract steep IRS penalties. We ensure all deposits are made accurately and on time — every time." },
      { title: "Gusto's Award-Winning Platform", desc: "Employees love Gusto's self-service portal for pay stubs, W-2s, and benefits enrollment. Employers love the simplicity of automated payroll." },
      { title: "Contractor & Employee Management", desc: "Seamlessly handle a mix of W-2 employees and 1099 contractors with proper classification to avoid costly misclassification penalties." },
      { title: "CPA-Overseen Payroll", desc: "Unlike standalone payroll services, your payroll is overseen by a licensed CPA ensuring proper alignment with your overall tax strategy." },
    ],
    process: [
      { num: "01", title: "Payroll Needs Assessment", desc: "Review your current staffing, pay schedule, compensation structure, and state registration requirements." },
      { num: "02", title: "Gusto Account Setup", desc: "Configure your Gusto account with company details, pay schedules, tax elections, and employee/contractor information." },
      { num: "03", title: "Employee Onboarding", desc: "Guide employees through Gusto self-onboarding including W-4s, direct deposit setup, and benefits enrollment." },
      { num: "04", title: "Ongoing Payroll & Compliance", desc: "Process each pay run, monitor tax deposits, file quarterly 941s and annual W-2s, and provide year-end reporting." },
    ],
    industries: ["Restaurants & Hospitality", "Dental Practices", "Staffing Companies", "Contractors & Construction", "IT Services", "Manufacturing", "Real Estate Firms"],
    documents: [
      "Employer EIN and Texas state payroll registration",
      "Employee W-4 forms and direct deposit details",
      "Contractor 1099 information (W-9 forms)",
      "Current pay rates, schedules, and benefits",
      "Prior payroll records (if switching from another system)",
    ],
    faqs: [
      { q: "Why do you recommend Gusto for payroll?", a: "Gusto is consistently rated #1 for small business payroll. It automates tax calculations, filings, and deposits while giving employees a great self-service experience." },
      { q: "How do I know if someone is an employee vs. a contractor?", a: "The IRS uses a multi-factor test based on behavioral control, financial control, and relationship type. We help you properly classify workers to avoid costly penalties." },
      { q: "What is an S-Corp reasonable salary?", a: "The IRS requires S-Corp owner-operators who perform services to pay themselves a 'reasonable salary' subject to payroll taxes before taking profit distributions. We help set the right amount." },
      { q: "What happens if I miss a payroll tax deposit?", a: "The IRS imposes Trust Fund penalties starting at 2% for deposits 1-5 days late, escalating to 15% for deposits more than 10 days late. We prevent this from happening." },
      { q: "Can you handle multi-state payroll?", a: "Yes. We handle payroll for businesses with employees in multiple states, managing each state's withholding and employer tax requirements." },
    ],
    related: ["business-formation", "bookkeeping", "tax-compliance"],
    uniqueData: {
      checklist: [
        "EIN obtained and Texas payroll account registered",
        "Gusto account created and company configured",
        "All employees onboarded with W-4 and direct deposit",
        "1099 contractors added with W-9 on file",
        "Pay schedule confirmed (weekly, bi-weekly, semi-monthly)",
        "First payroll run reviewed and approved",
      ],
      calendar: [
        { date: "Bi-weekly", task: "Regular Employee Pay Run Processing" },
        { date: "Monthly", task: "Payroll Tax Deposit (if monthly depositor)" },
        { date: "Quarterly", task: "Form 941 Payroll Tax Return Filing" },
        { date: "January 31", task: "W-2 Employee & 1099-NEC Contractor Filing" },
      ],
    },
  },

  "bookkeeping": {
    slug: "bookkeeping",
    title: "Bookkeeping & Accounting",
    primaryKeyword: "bookkeeping accounting CPA Irving TX small business",
    overviewTitle: "Clean, Accurate Books — The Foundation of Every Successful Business",
    overview: "At VS Tax CPA LLC, we provide comprehensive monthly bookkeeping and accounting services that give you a clear, real-time picture of your business finances. Clean books are not just good practice — they're the foundation for smart tax planning, accurate tax filings, and confident business decisions.",
    whatWeOffer: [
      { title: "Monthly Bookkeeping", desc: "Accurate categorization of all income and expenses, bank and credit card reconciliations, and real-time financial reporting each month." },
      { title: "Financial Statement Preparation", desc: "Monthly Profit & Loss (Income Statement), Balance Sheet, and Cash Flow Statement — prepared in accordance with GAAP." },
      { title: "Accounts Receivable & Payable", desc: "Tracking of outstanding invoices, vendor bills, and aging reports to optimize your business cash flow." },
      { title: "Year-End Closing & Tax Prep", desc: "Complete year-end close procedures ensuring your books are clean, reconciled, and fully ready for accurate tax return preparation." },
    ],
    benefits: [
      { title: "Real-Time Financial Clarity", desc: "Know exactly where your business stands financially at any given moment — no more flying blind or guessing your profitability." },
      { title: "Tax-Ready Books", desc: "When your books are clean year-round, tax preparation is faster, cheaper, and less stressful — with fewer missed deductions." },
      { title: "Better Business Decisions", desc: "Accurate monthly financials help you make smarter pricing decisions, control costs, and identify your most and least profitable revenue streams." },
      { title: "CPA-Grade Accuracy", desc: "Your books are maintained by accounting professionals under the direct supervision of a licensed CPA — not just a data entry clerk." },
    ],
    process: [
      { num: "01", title: "Books Assessment", desc: "Review your current accounting software, chart of accounts, and existing records to understand your starting point." },
      { num: "02", title: "Setup & Cleanup", desc: "Set up or clean up QuickBooks, clean historical transactions, and establish a proper chart of accounts for your industry." },
      { num: "03", title: "Monthly Bookkeeping Cycle", desc: "Each month: import transactions, categorize and reconcile, generate financial statements, and flag any issues." },
      { num: "04", title: "Reporting & Review", desc: "Deliver your monthly financial package with a brief summary of key metrics, notable variances, and any recommended actions." },
    ],
    industries: ["Restaurants & Hospitality", "Real Estate & Property Management", "Dental Practices", "IT Services & Consultants", "Contractors", "Staffing Companies", "Manufacturing", "Artists & Creatives"],
    documents: [
      "Bank and credit card statements",
      "Sales and revenue records",
      "Expense receipts and vendor invoices",
      "Existing accounting software access (QuickBooks, Xero, etc.)",
      "Prior year financial statements or tax returns",
    ],
    faqs: [
      { q: "What accounting software do you use?", a: "We primarily use QuickBooks Online, but also work with Xero, FreshBooks, and Wave. We'll recommend the best platform for your business size and industry." },
      { q: "How often will I receive financial reports?", a: "You'll receive monthly financial statements (P&L, Balance Sheet, Cash Flow) within 10 business days of month-end." },
      { q: "Do I need clean bookkeeping if I'm a cash-basis taxpayer?", a: "Yes. Even cash-basis businesses benefit from organized books to track profitability, manage cash flow, and prepare accurate tax returns." },
      { q: "What's the difference between bookkeeping and accounting?", a: "Bookkeeping is the recording of daily transactions. Accounting involves interpreting, classifying, and summarizing those records for financial decision-making. We provide both." },
      { q: "My books are a mess. Can you fix them?", a: "Absolutely. We specialize in bookkeeping cleanup and catch-up services — getting your books from chaos to fully reconciled and organized." },
    ],
    related: ["tax-compliance", "fractional-cfo", "payroll-services"],
    uniqueData: {
      checklist: [
        "Chart of accounts set up for your industry",
        "All bank and credit card accounts connected",
        "Historical transactions imported and categorized",
        "Accounts receivable aging report generated",
        "Monthly close checklist established",
        "Financial statement template configured",
      ],
      calendar: [
        { date: "Monthly (by 10th)", task: "Prior Month Bookkeeping Reconciliation & Reports" },
        { date: "Quarterly", task: "Quarterly Financial Review & Tax Projection" },
        { date: "December", task: "Year-End Accrual Adjustments & Final Reconciliation" },
        { date: "January", task: "Year-End Financial Package Delivered for Tax Prep" },
      ],
    },
  },

  "fractional-cfo": {
    slug: "fractional-cfo",
    title: "Fractional CFO Services",
    primaryKeyword: "fractional CFO CPA advisory Irving TX strategic finance",
    overviewTitle: "Strategic Financial Leadership Without the Full-Time CFO Cost",
    overview: "A Chief Financial Officer provides the strategic financial vision that separates growing companies from stagnant ones — but most small and mid-sized businesses can't justify a full-time CFO. VS Tax CPA LLC's Fractional CFO service gives you high-level financial strategy, forecasting, and advisory on a flexible, part-time basis.",
    whatWeOffer: [
      { title: "Financial Forecasting & Budgeting", desc: "Build detailed 12-month cash flow projections, annual budgets, and scenario models to navigate growth confidently." },
      { title: "KPI Dashboard & Performance Tracking", desc: "Identify your business's key performance indicators and build a monthly dashboard to track progress and diagnose problems early." },
      { title: "Strategic Financial Advisory", desc: "Monthly or quarterly strategy sessions covering pricing decisions, expansion planning, cost control, and capital allocation." },
      { title: "Funding & Lender Preparation", desc: "Prepare financial models, projections, and documentation needed for SBA loans, bank financing, investor decks, and lines of credit." },
    ],
    benefits: [
      { title: "CFO-Level Insight at a Fraction of the Cost", desc: "Access the strategic financial expertise of a seasoned CFO for a few thousand dollars per month — not a $200,000+ salary." },
      { title: "Cash Flow Mastery", desc: "Understand your cash conversion cycle, anticipate cash crunches months in advance, and make strategic capital allocation decisions." },
      { title: "Investor & Lender Credibility", desc: "Professional financial models and projections built by a CPA dramatically improve your credibility with banks, investors, and potential buyers." },
      { title: "Data-Driven Decisions", desc: "Move from gut-feel to data-driven decision making with clear financial metrics, trend analysis, and forward-looking projections." },
    ],
    process: [
      { num: "01", title: "Financial Diagnostic", desc: "Comprehensive review of your current financials, cash flow patterns, cost structure, pricing, and business model." },
      { num: "02", title: "Strategy & Roadmap", desc: "Develop a customized financial roadmap with 90-day priorities, annual goals, and 3-year projections." },
      { num: "03", title: "Implementation Support", desc: "Work alongside your team to implement financial systems, dashboards, and reporting cadences." },
      { num: "04", title: "Ongoing Advisory", desc: "Regular CFO advisory sessions reviewing actual vs. budget, refining forecasts, and making strategic recommendations." },
    ],
    industries: ["IT Services & SaaS Startups", "Dental Practices & Healthcare", "Restaurants & Franchise", "Real Estate & Property Development", "Staffing Companies", "Manufacturing", "Contractors"],
    documents: [
      "Last 2-3 years of financial statements",
      "Current revenue and expense run-rate",
      "Existing budget or forecast (if any)",
      "Organizational chart and key personnel costs",
      "Outstanding debt and credit facility details",
    ],
    faqs: [
      { q: "When does a business need a Fractional CFO?", a: "Typically when revenue exceeds $500K–$1M, when you're preparing to raise capital or seek financing, when cash flow is unpredictable, or when you're planning significant growth or acquisition." },
      { q: "What is the difference between a bookkeeper, accountant, and CFO?", a: "Bookkeepers record transactions. Accountants ensure accuracy and prepare tax returns. A CFO provides strategic financial leadership — forecasting, capital strategy, and growth planning." },
      { q: "How many hours per month does a Fractional CFO engagement require?", a: "Engagements typically range from 4–20 hours per month depending on the complexity of your business and the scope of work required." },
      { q: "Can a Fractional CFO help with SBA loan applications?", a: "Yes. We prepare the detailed financial projections, business plans, and documentation that lenders require for SBA 7(a) and 504 loan approvals." },
      { q: "What financial models do you build?", a: "We build revenue models, P&L projections, cash flow forecasts, unit economics models, break-even analyses, and scenario planning models." },
    ],
    related: ["bookkeeping", "tax-planning", "business-formation"],
    uniqueData: {
      tips: [
        { category: "Cash Flow", tip: "Maintain a 90-day cash flow forecast updated weekly to anticipate shortfalls before they become crises." },
        { category: "Pricing", tip: "Analyze gross margin by service line or product to identify your most profitable offerings and double down on them." },
        { category: "Growth", tip: "Before hiring, model the full loaded cost of each new employee (salary + benefits + taxes + overhead) against projected revenue impact." },
        { category: "Financing", tip: "Maintain clean, CPA-reviewed financials year-round to be 'lender ready' and secure better loan terms when the opportunity arises." },
      ],
      deadlines: [
        { date: "Monthly", event: "Financial Review & KPI Dashboard Update" },
        { date: "Quarterly", event: "Budget vs. Actual Review & Forecast Refresh" },
        { date: "Annually", event: "Annual Budget & 3-Year Strategic Financial Plan" },
        { date: "On Demand", event: "Lender & Investor Readiness Package Preparation" },
      ],
    },
  },

  "irs-representation": {
    slug: "irs-representation",
    title: "IRS Representation & Tax Relief",
    primaryKeyword: "IRS representation tax relief audit CPA Irving TX",
    overviewTitle: "Expert IRS Representation & Tax Problem Resolution",
    overview: "Receiving a notice from the IRS or state tax authority is stressful and confusing — but you don't have to face it alone. VS Tax CPA LLC provides professional IRS representation, handling all communications with the IRS on your behalf to resolve tax notices, audits, unfiled returns, and tax debts as efficiently and favorably as possible.",
    whatWeOffer: [
      { title: "IRS Notice & Letter Response", desc: "Professional response to all types of IRS and state tax notices including CP2000, CP504, LT11, and audit notification letters." },
      { title: "Audit Representation", desc: "Full representation during correspondence, office, and field audits — we communicate directly with the IRS so you don't have to." },
      { title: "Unfiled Tax Returns", desc: "Prepare and file all back tax returns to bring you into compliance and stop the IRS's estimate process (substitute for return)." },
      { title: "Tax Debt Resolution", desc: "Negotiate Installment Agreements, Offer in Compromise (OIC), Currently Not Collectible (CNC) status, and penalty abatement with the IRS." },
    ],
    benefits: [
      { title: "Stop IRS Levies & Garnishments", desc: "Prompt professional action can stop or prevent IRS bank levies, wage garnishments, and property liens that can devastate your finances." },
      { title: "Penalty Abatement", desc: "The IRS waives penalties in many situations. We identify and pursue all available penalty abatement options to reduce your balance owed." },
      { title: "Licensed CPA Authority", desc: "As a licensed CPA, Vethavalli Ramakrishnan has the legal authority to represent you before all IRS divisions and state tax authorities." },
      { title: "Confidential & Strategic", desc: "We develop a strategic approach to each case, ensuring the IRS receives only what they're entitled to — nothing more." },
    ],
    process: [
      { num: "01", title: "Notice Review & Assessment", desc: "Analyze the IRS notice or audit scope to identify exactly what the IRS is questioning and assess the best response strategy." },
      { num: "02", title: "Power of Attorney", desc: "File IRS Form 2848 so we can communicate directly with the IRS on your behalf — keeping you out of stressful phone calls and meetings." },
      { num: "03", title: "Response & Negotiation", desc: "Prepare the appropriate response, gather supporting documentation, and negotiate with the IRS for the best possible outcome." },
      { num: "04", title: "Resolution & Future Protection", desc: "Achieve resolution, ensure future compliance, and implement strategies to prevent recurrence." },
    ],
    industries: ["Self-Employed & Freelancers", "Real Estate Investors", "Restaurants", "Contractors", "IT Services", "Manufacturing", "Artists & Creatives"],
    documents: [
      "All IRS notices and letters received (with dates)",
      "Last 3-5 years of tax returns",
      "Bank statements for the period in question",
      "Supporting documentation for disputed deductions",
      "Prior correspondence with the IRS",
    ],
    faqs: [
      { q: "What should I do if I receive an IRS notice?", a: "Don't ignore it. Respond promptly (usually within 30-60 days of the notice date). Call us immediately so we can review the notice and determine the best response." },
      { q: "What is an Offer in Compromise (OIC)?", a: "An OIC allows qualifying taxpayers to settle their IRS tax debt for less than the full amount owed. Approval depends on ability to pay, income, expenses, and asset equity." },
      { q: "What is penalty abatement?", a: "The IRS offers First-Time Penalty Abatement for taxpayers with a clean compliance history and Reasonable Cause Abatement for circumstances beyond your control (illness, disaster, etc.)." },
      { q: "Can you represent me in a tax audit?", a: "Yes. As a licensed CPA, we represent clients in correspondence audits, office audits, and field audits — handling all IRS communication on your behalf." },
      { q: "What if I haven't filed taxes in several years?", a: "The IRS typically requires the last 6 years of returns to be filed for compliance. We prepare all back returns and negotiate the most favorable resolution of resulting tax debts." },
    ],
    related: ["tax-compliance", "tax-planning", "bookkeeping"],
    uniqueData: {
      checklist: [
        "All IRS notices collected and reviewed",
        "Filing compliance status assessed (unfiled years identified)",
        "IRS account transcript obtained via POA",
        "Response strategy determined",
        "Form 2848 (Power of Attorney) filed",
        "Resolution agreement or abatement negotiated",
      ],
      calendar: [
        { date: "Within 24 hrs", task: "Emergency Consultation & Notice Review" },
        { date: "Within 3 days", task: "POA Filing & IRS Account Access" },
        { date: "Day 7-14", task: "Response Preparation & Documentation Gathering" },
        { date: "Day 30", task: "IRS Response Submission (before deadline)" },
      ],
    },
  },

  "sales-tax-1099": {
    slug: "sales-tax-1099",
    title: "Sales Tax & 1099 Filing",
    primaryKeyword: "sales tax filing 1099 filing CPA Irving TX small business",
    overviewTitle: "Sales Tax Compliance & Year-End 1099 Filing Made Simple",
    overview: "Sales tax compliance and 1099 filing are two areas where small businesses frequently face unexpected penalties. VS Tax CPA LLC manages your state and local sales tax registrations, accurate collections, and timely returns — plus handles all year-end 1099-NEC and 1099-MISC preparation and filing for your contractors and vendors.",
    whatWeOffer: [
      { title: "Sales Tax Registration & Setup", desc: "Register your business for sales tax collection in Texas and any additional states where you have nexus (economic or physical presence)." },
      { title: "Sales Tax Return Preparation & Filing", desc: "Accurate monthly, quarterly, or annual Texas sales tax returns (and multi-state returns) filed on time — every time." },
      { title: "1099-NEC & 1099-MISC Preparation", desc: "Year-end preparation and IRS/state e-filing of all 1099 forms for contractors, freelancers, vendors, and landlords you've paid during the year." },
      { title: "1099 Recipient Delivery", desc: "Prepare and deliver paper or electronic 1099 copies to all recipients by the January 31 deadline, with full IRS e-filing included." },
    ],
    benefits: [
      { title: "Avoid Costly Penalties", desc: "Late or incorrect 1099s carry IRS penalties of $50–$290 per form. We ensure every form is accurate and filed on time." },
      { title: "Multi-State Sales Tax Compliance", desc: "Post-Wayfair economic nexus rules mean you may owe sales tax in states where you have no physical presence. We identify your obligations and keep you compliant." },
      { title: "No More Year-End Scramble", desc: "We collect W-9s from your contractors throughout the year so January 1099 filing is seamless — no last-minute panic." },
      { title: "Full IRS E-Filing", desc: "All 1099s are filed electronically with the IRS and applicable state tax authorities, with confirmation provided for your records." },
    ],
    process: [
      { num: "01", title: "Contractor & Vendor Review", desc: "Review all payments made to contractors and vendors during the year to identify who requires a 1099 form." },
      { num: "02", title: "W-9 Collection", desc: "Collect or verify W-9 information (name, address, TIN) for all 1099-eligible recipients." },
      { num: "03", title: "1099 Preparation & Verification", desc: "Prepare all 1099-NEC and 1099-MISC forms, verify accuracy, and resolve any TIN mismatches." },
      { num: "04", title: "Filing & Delivery", desc: "E-file all 1099s with the IRS by January 31, deliver copies to recipients, and provide you with a filing confirmation package." },
    ],
    industries: ["Restaurants & Hospitality", "Real Estate & Property Managers", "Contractors", "IT Services & Consultants", "Staffing Companies", "Artists & Creatives", "Manufacturing"],
    documents: [
      "List of all contractors/freelancers paid $600+ during the year",
      "W-9 forms from all contractors",
      "Total amounts paid to each contractor by payment category",
      "Business EIN and state tax ID",
      "Existing sales tax registration numbers (if applicable)",
    ],
    faqs: [
      { q: "Who requires a 1099?", a: "Generally, any contractor, freelancer, or unincorporated business you paid $600 or more during the tax year requires a 1099-NEC. Rent payments of $600+ to a landlord require a 1099-MISC." },
      { q: "Do I need to issue a 1099 to an LLC or corporation?", a: "Generally no for corporations (with some exceptions). For LLCs, it depends on how they're taxed — single-member LLCs taxed as sole proprietors require 1099s." },
      { q: "What is a W-9 and when should I collect it?", a: "A W-9 provides the contractor's legal name, address, and Tax ID. Best practice is to collect W-9s before making any payment to a new contractor." },
      { q: "What is economic nexus for sales tax?", a: "After the South Dakota v. Wayfair Supreme Court decision, states can require sales tax collection based on economic activity (typically $100,000 in sales OR 200 transactions) even without physical presence." },
      { q: "Does Texas charge sales tax?", a: "Texas has a 6.25% state sales tax plus local tax up to 2%, for a maximum of 8.25%. Most tangible personal property and some services are taxable. We determine your specific obligations." },
    ],
    related: ["tax-compliance", "bookkeeping", "payroll-services"],
    uniqueData: {
      checklist: [
        "All contractors paid $600+ identified",
        "W-9 collected and TIN verified for each contractor",
        "Payment amounts reconciled to books",
        "Sales tax nexus assessment completed",
        "State sales tax registration completed (if required)",
        "1099s prepared, e-filed, and delivered",
      ],
      calendar: [
        { date: "January 31", task: "1099-NEC Issued to Recipients & Filed with IRS" },
        { date: "February 28", task: "1099-MISC (paper) Filing Deadline with IRS" },
        { date: "Monthly/Quarterly", task: "Texas Sales Tax Return Filing" },
        { date: "Year-Round", task: "W-9 Collection from New Contractors" },
      ],
    },
  },
};
